image: gitlab.ipb.uni-bonn.de:4567/global/docker-images:ipb_default

build_release:
  script:
  - export TERM=xterm
  - export SHELL=/bin/bash
  - apt-get update -yq
  - apt-get install -y libeigen3-dev libboost-filesystem-dev libboost-system-dev libglew-dev xvfb mesa-utils
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DOPENGL_VERSION=330 -DFORCE_BUILD_TEST=On .. 
  - make
  # finally run tests.
  - xvfb-run -s "-screen 0 640x480x24" ctest -VV
  stage: build
  tags:   
    - docker

build_debug:
  script:
  - export TERM=xterm
  - export SHELL=/bin/bash
  - apt-get update -yq
  - apt-get install -y libeigen3-dev libboost-filesystem-dev libboost-system-dev libglew-dev xvfb mesa-utils
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DOPENGL_VERSION=330 -DFORCE_BUILD_TEST=On .. 
  - make
  # finally run tests.
  - xvfb-run -s "-screen 0 640x480x24" ctest -VV
  stage: build
  tags:   
    - docker


